### ISSUE TITLE
v1.8 missing on PYPI

### ISSUE THREAD

**Issue by webknjaz** [jaraco/tempora#4]
It seems you unpublished v1.8, which is still shown on the badge in README.

This causes failure to install `portend`: cherrypy/cherrypy#1606

**Comment by jaraco** [comment]
Here's [where it should have been deployed](https://travis-ci.org/jaraco/tempora/jobs/246811289) and [I see the files here](https://pypi.org/project/tempora/#files) and [here](https://pypi.python.org/pypi/tempora/1.8).

Aha - but the 1.7.1 was released after 1.8 (due to the order in which Travis discovered the tags)... leading to this situation:

![image](https://user-images.githubusercontent.com/308610/27923315-fa45083a-624b-11e7-851b-556fb0ef6fcf.png)

**Comment by jaraco** [comment]
When I query for [simple](https://pypi.python.org/simple/tempora/), it does show 1.8.
